AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for CCE Challenge

Resources:
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  DataTableArn:
    Value: !GetAtt DataTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DataTableArn
  DataTableName:
    Value: !Ref DataTable
    Export:
      Name: !Sub ${AWS::StackName}-DataTableName