AWSTemplateFormatVersion: '2010-09-09'
Description: Master template for CCE Challenge

Resources:
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: dynamodb.yaml

  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iam_roles.yaml
      Parameters:
        DataTableArn: !ImportValue !Sub ${AWS::StackName}-DataTableArn

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambda.yaml
      Parameters:
        DataTableName: !ImportValue !Sub ${AWS::StackName}-DataTableName
        DataTableArn: !ImportValue !Sub ${AWS::StackName}-DataTableArn

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: api_gateway.yaml
      Parameters:
        StoreDataFunctionArn: !ImportValue !Sub ${AWS::StackName}-StoreDataFunctionArn

Outputs:
  ApiEndpoint:
    Description: Endpoint URL for the API
    Value: !ImportValue !Sub ${AWS::StackName}-ApiEndpoint